apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: homelab
  labels:
    name: grafana
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: grafana
  template:
    metadata:
      labels:
        name: grafana
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: grafana # https://github.com/grafana/grafana
          image: "grafana/grafana:11.6.0" # 
          env: []
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /var/lib/grafana/
              name: config
            - mountPath: /etc/grafana/
              name: init
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: grafana-local-config-pvc
        - name: init
          configMap:
            name: grafana-configmap 
            items:
              - key: grafana.ini
                path: grafana.ini
