apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-local-config-pvc
  namespace: homelab
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: grafana-local-storage
  volumeName: grafana-local-config-pv
  resources:
    requests:
      storage: 2Gi
