apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: homelab
  labels:
    name: grafana-svc
  annotations:
    name: grafana-svc
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      # nodePort: 30000
  selector:
    name: grafana
  sessionAffinity: None
