apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - apiextensions.k8s.io-v1.CustomResourceDefinition-podlogs.monitoring.grafana.com.yaml
  - apps-v1.StatefulSet-pyroscope-alloy.yaml
  - rbac.authorization.k8s.io-v1.ClusterRoleBinding-pyroscope-alloy.yaml
  - rbac.authorization.k8s.io-v1.ClusterRole-pyroscope-alloy.yaml
  - v1.ConfigMap-alloy-Config-pyroscope-FIXED.yaml
  - v1.ServiceAccount-pyroscope-alloy.yaml
  - v1.Service-pyroscope-alloy-cluster.yaml
  - v1.Service-pyroscope-alloy.yaml