apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/instance: pyroscope
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/version: v1.1.1
    helm.sh/chart: alloy-0.3.2
  name: pyroscope-alloy
  namespace: homelab
