apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - v1.Service-pyroscope.yaml
  - v1.Service-pyroscope-memberlist.yaml
  - v1.Service-pyroscope-headless.yaml
  - v1.ServiceAccount-pyroscope.yaml
  - v1.ConfigMap-pyroscope-config.yaml
  - v1.ConfigMap-pyroscope-overrides-config.yaml
  - policy-v1.PodDisruptionBudget-pyroscope.yaml
  - apps-v1.StatefulSet-pyroscope.yaml
