apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: pyroscope
    app.kubernetes.io/managed-by: Helmraiser
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/version: 1.13.1
    helm.sh/chart: pyroscope-1.13.1
  name: pyroscope-memberlist
  namespace: homelab
spec:
  clusterIP: None
  ports:
  - name: memberlist
    port: 7946
    protocol: TCP
    targetPort: 7946
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: pyroscope
    app.kubernetes.io/name: pyroscope
  type: ClusterIP
